blogproject/blog/urls.py
from django.conf.urls import url
from blog import views
urlpatterns = [
    url(r'^$',views.index,name = 'index'),
    url(r'^about$', views.about,name='about'),
    url(r'^contact$', views.contact,name='contact'),
    url(r'^full_width$', views.full_width,name = 'full_width'),
    url(r'^post/(?P<pk>[0-9]+)$', views.detail,name = 'detail'),
]

blogproject/blogproject/urls.py
from django.conf.urls import url,include
from django.contrib import admin
import blog

urlpatterns = [
    url(r'^admin/', admin.site.urls),
  #  url(r'^blog/',include('blog.urls')),
    url(r'^$', include('blog.urls','blog')),
    url(r'^blog/', include('blog.urls')),
]

blogproject/blog/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
#分类
class Category(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name
#标签
class Tag(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name
#文章
class Post(models.Model):
    #文章标题
    title = models.CharField(max_length=100)
    #创建时间
    create_time = models.DateTimeField()
    #修改时间
    modified_time = models.DateTimeField()
    #文章摘要 可以为空
    excerpt = models.CharField(max_length=200,blank = True)
    #文章对应的分类
    category = models.ForeignKey(Category)
    #文章对应的tag 可以为空
    tag = models.ManyToManyField(Tag,blank=True)

    author = models.ForeignKey(User)

    body = models.TextField(default='')

    def __str__(self):
        return self.title

blogproject/blog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Post
from markdown import markdown
# Create your views here.

def index(request):
    post_list = Post.objects.all().order_by('-create_time') #按时间倒序排列
    return render(request,'blog/index.html',context = {'post_list':post_list})
def detail(request,pk):
    post = Post.objects.get(id=pk)

    post.body = markdown(post.body,
                                  extensions=[
                                     'markdown.extensions.extra',
                                     'markdown.extensions.codehilite',
                                     'markdown.extensions.toc',
                                  ])
    post.excerpt = markdown(post.excerpt,
                         extensions=[
                             'markdown.extensions.extra',
                             'markdown.extensions.codehilite',
                             'markdown.extensions.toc',
                         ])
    return render(request,'blog/detail.html',context = {'post':post})

def full_width(request):
    return render(request,'blog/full-width.html')
def contact(request):
    return render(request,'blog/contact.html')
def about(request):
    return render(request,'blog/about.html')

blogproject/templates/base.html
{% load blog_tags %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>Black &amp; White</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css'%}">
    <link rel="stylesheet" href="{%  static 'blog/css/custom.css'%}">
    <link rel="stylesheet" href="{% static 'blog/css/highlights/github.css' %}">

    <!-- js -->
    <script src="{% static 'blog/js/jquery-2.1.3.min.js'%}"></script>
    <script src="{%  static 'blog/js/bootstrap.min.js' %}"></script>
    <script src="{%  static 'blog/js/pace.min.js' %}"></script>
    <script src="{%  static 'blog/js/modernizr.custom.js' %}"></script>
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'index' %}"><b>Black</b> &amp; White</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">

                            <li class="cl-effect-11"><a href="{% url 'index'%}" data-hover="首页">首页</a></li>

                            <li class="cl-effect-11"><a href="{% url 'full_width'%}" data-hover="博客">博客</a></li>

                            <li class="cl-effect-11"><a href="{% url 'about'%}" data-hover="关于">关于</a></li>

                            <li class="cl-effect-11"><a href="{% url 'contact'%} " data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="#">
                            <input type="search" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
<div class="copyrights">Modified by <a href="http://zmrenwu.com/">追梦人物的博客</a></div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
               {% block main %}
                {% endblock main %}
            </main>
            <aside class="col-md-4">
                {% block toc %}
                {% endblock toc %}
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2017 - 采集自<a href="http://www.cssmoban.com/"
                                                        target="_blank" title="模板之家">模板之家</a>
                    - 由<a href="http://zmrenwu.com/" title="网页模板" target="_blank">追梦人物的博客</a>修改
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>

            <li><a href=" {% url 'index'%}">首页</a></li>

            <li><a href="{% url 'full_width'%}">博客111</a></li>

            <li><a href=" {% url 'about'%}">关于</a></li>

            <li><a href=" {% url 'contact'%}">联系</a></li>
        </ul>
    </nav>
</div>

<script src="{%  static '/blog/js/script.js' %}"></script>

</body>
</html>

blogproject/templates/blog/about.html
{% extends 'base.html' %}
{% load static %}
{% block main %}
    <h1 class="page-title">About Me</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<figure class="img-responsive-center">
									<img class="img-responsive" src="../../blog/static/blog/img/me.jpg" alt="Developer Image">
								</figure>
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<div class="height-40px"></div>
								<h2 class="title text-center">Social</h2>
								<ul class="social">
									<li class="facebook"><a href="#"><span class="ion-social-facebook"></span></a></li>
									<li class="twitter"><a href="#"><span class="ion-social-twitter"></span></a></li>
									<li class="google-plus"><a href="#"><span class="ion-social-googleplus"></span></a></li>
									<li class="tumblr"><a href="#"><span class="ion-social-tumblr"></span></a></li>
								</ul>
							</div>
						</article>
{% endblock main %}

blogproject/templates/blog/contact.html
{% extends 'base.html' %}
{% load static %}
{% block main %}
    <h1 class="page-title">Contact</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<form action="#" method="post" class="contact-form">
									<div class="row">
										<div class="col-md-6 col-md-offset-3">
											<input type="text" name="name" placeholder="Name" required>
											<input type="email" name="email" placeholder="Email" required>
											<input type="text" name="subject" placeholder="Subject" required>
											<textarea name="message" rows="7" placeholder="Your Message" required></textarea>
											<button class="btn-send btn-5 btn-5b ion-ios-paperplane"><span>Drop Me a Line</span></button>
										</div>
									</div>	<!-- row -->
								</form>
							</div>
						</article>
{% endblock main %}

blogproject/templates/blog/detail.html
{% extends 'base.html' %}
{% block main %}
     <article class="post post-1">
                    <header class="entry-header">
                        <h1 class="entry-title">{{ post.title }}</h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#">Django 博客教程</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date">{{ post.create_time }}</time></a></span>
                            <span class="post-author"><a href="#">{{ post.author }}</a></span>
                            <span class="comments-link"><a href="#">4 评论</a></span>
                            <span class="views-count"><a href="#">588 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        {{ post.body|safe }}

                    </div>
                </article>
                <section class="comment-area" id="comment-area">
                    <hr>
                    <h3>发表评论</h3>
                    <form action="#" method="post" class="comment-form">
                        <div class="row">
                            <div class="col-md-4">
                                <label for="id_name">名字：</label>
                                <input type="text" id="id_name" name="name" required>
                            </div>
                            <div class="col-md-4">
                                <label for="id_email">邮箱：</label>
                                <input type="email" id="id_email" name="email" required>
                            </div>
                            <div class="col-md-4">
                                <label for="id_url">网址：</label>
                                <input type="text" id="id_url" name="url">
                            </div>
                            <div class="col-md-12">
                                <label for="id_comment">评论：</label>
                                <textarea name="comment" id="id_comment" required></textarea>
                                <button type="submit" class="comment-btn">发表</button>
                            </div>
                        </div>    <!-- row -->
                    </form>
                    <div class="comment-list-panel">
                        <h3>评论列表，共 <span>4</span> 条评论</h3>
                        <ul class="comment-list list-unstyled">
                            <li class="comment-item">
                                <span class="nickname">追梦人物</span>
                                <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">2017年3月12日 14:56</time>
                                <div class="text">
                                    文章观点又有道理又符合人性，这才是真正为了表达观点而写，不是为了迎合某某知名人士粉丝而写。我觉得如果琼瑶是前妻，生了三孩子后被一不知名的女人挖了墙角，我不信谁会说那个女人是追求真爱，说同情琼瑶骂小三的女人都是弱者。
                                </div>
                            </li>
                            <li class="comment-item">
                                <span class="nickname">zmrenwu</span>
                                <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">2017年3月11日 23:56</time>
                                <div class="text">
                                    本能有可能会冲破格局，但格局有时候也会拘住本能。
                                </div>
                            </li>
                            <li class="comment-item">
                                <span class="nickname">蝙蝠侠</span>
                                <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">2017年3月9日 8:56</time>
                                <div class="text">
                                    其实真理一般是属于沉默的大多数的。那些偏激的观点只能吸引那些同样偏激的人。前几年琼瑶告于妈抄袭，大家都表示大快人心，说明吃瓜观众都只是就事论事，并不是对琼瑶有偏见。
                                </div>
                            </li>
                            <li class="comment-item">
                                <span class="nickname">长江七号</span>
                                <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">2017年2月12日 12:56</time>
                                <div class="text">
                                    观点我很喜欢！就是哎嘛本来一清二楚的，来个小三小四乱七八糟一团乱麻夹缠不清，简直麻烦要死
                                </div>
                            </li>
                        </ul>
                    </div>
                </section>
{% endblock main %}

blogproject/templates/blog/detail2.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Black &amp; White</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="{% static '/blog/css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static '/blog/css/pace.css'%}">
    <link rel="stylesheet" href="{% static '/blog/css/custom.css'%}">

    <!-- js -->
    <script src="{% static '/blog/js/jquery-2.1.3.min.js'%}"></script>
    <script src="{% static '/blog/js/bootstrap.min.js'%}"></script>
    <script src="{% static '/blog/js/pace.min.js'%}"></script>
    <script src="{% static '/blog/js/modernizr.custom.js'%}"></script>
</head>

<body id="single">
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="index.html"><b>Black</b> &amp; White</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'index' %}" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="{% url 'full_width' %}" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="{% url 'about' %}" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="{% url 'contact' %}" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="#">
                            <input type="search" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                <article class="post post-1">
                    <header class="entry-header">
                        <h1 class="entry-title">{{ post.title }}</h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#">Django 博客教程</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date">{{ post.create_time }}</time></a></span>
                            <span class="post-author"><a href="#">{{ post.author }}</a></span>
                            <span class="comments-link"><a href="#">4 评论</a></span>
                            <span class="views-count"><a href="#">588 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        {{ post.body }}
                    </div>
                </article>
                <section class="comment-area" id="comment-area">
                    <hr>
                    <h3>发表评论</h3>
                    <form action="#" method="post" class="comment-form">
                        <div class="row">
                            <div class="col-md-4">
                                <label for="id_name">名字：</label>
                                <input type="text" id="id_name" name="name" required>
                            </div>
                            <div class="col-md-4">
                                <label for="id_email">邮箱：</label>
                                <input type="email" id="id_email" name="email" required>
                            </div>
                            <div class="col-md-4">
                                <label for="id_url">网址：</label>
                                <input type="text" id="id_url" name="url">
                            </div>
                            <div class="col-md-12">
                                <label for="id_comment">评论：</label>
                                <textarea name="comment" id="id_comment" required></textarea>
                                <button type="submit" class="comment-btn">发表</button>
                            </div>
                        </div>    <!-- row -->
                    </form>
                    <div class="comment-list-panel">
                        <h3>评论列表，共 <span>4</span> 条评论</h3>
                        <ul class="comment-list list-unstyled">
                            <li class="comment-item">
                                <span class="nickname">追梦人物</span>
                                <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">2017年3月12日 14:56</time>
                                <div class="text">
                                    文章观点又有道理又符合人性，这才是真正为了表达观点而写，不是为了迎合某某知名人士粉丝而写。我觉得如果琼瑶是前妻，生了三孩子后被一不知名的女人挖了墙角，我不信谁会说那个女人是追求真爱，说同情琼瑶骂小三的女人都是弱者。
                                </div>
                            </li>
                            <li class="comment-item">
                                <span class="nickname">zmrenwu</span>
                                <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">2017年3月11日 23:56</time>
                                <div class="text">
                                    本能有可能会冲破格局，但格局有时候也会拘住本能。
                                </div>
                            </li>
                            <li class="comment-item">
                                <span class="nickname">蝙蝠侠</span>
                                <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">2017年3月9日 8:56</time>
                                <div class="text">
                                    其实真理一般是属于沉默的大多数的。那些偏激的观点只能吸引那些同样偏激的人。前几年琼瑶告于妈抄袭，大家都表示大快人心，说明吃瓜观众都只是就事论事，并不是对琼瑶有偏见。
                                </div>
                            </li>
                            <li class="comment-item">
                                <span class="nickname">长江七号</span>
                                <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">2017年2月12日 12:56</time>
                                <div class="text">
                                    观点我很喜欢！就是哎嘛本来一清二楚的，来个小三小四乱七八糟一团乱麻夹缠不清，简直麻烦要死
                                </div>
                            </li>
                        </ul>
                    </div>
                </section>
            </main>
            <aside class="col-md-4">
                <div class="widget widget-content">
                    <h3 class="widget-title">文章目录</h3>
                    <ul>
                        <li>
                            <a href="#">教程特点</a>
                        </li>
                        <li>
                            <a href="#">谁适合这个教程</a>
                        </li>
                        <li>
                            <a href="#">在线预览</a>
                        </li>
                        <li>
                            <a href="#">资源列表</a>
                        </li>
                        <li>
                            <a href="#">获取帮助</a>
                        </li>
                    </ul>
                </div>
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    <ul>
                        <li>
                            <a href="#">Django 博客开发入门教程：前言</a>
                        </li>
                        <li>
                            <a href="#">Django 博客使用 Markdown 自动生成文章目录</a>
                        </li>
                        <li>
                            <a href="#">部署 Django 博客</a>
                        </li>
                    </ul>
                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    <ul>
                        <li>
                            <a href="#">2017 年 5 月</a>
                        </li>
                        <li>
                            <a href="#">2017 年 4 月</a>
                        </li>
                        <li>
                            <a href="#">2017 年 3 月</a>
                        </li>
                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    <ul>
                        <li>
                            <a href="#">Django 博客教程 <span class="post-count">(13)</span></a>
                        </li>
                        <li>
                            <a href="#">Python 教程 <span class="post-count">(11)</span></a>
                        </li>
                        <li>
                            <a href="#">Django 用户认证 <span class="post-count">(8)</span></a>
                        </li>
                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    <ul>
                        <li>
                            <a href="#">Django</a>
                        </li>
                        <li>
                            <a href="#">Python</a>
                        </li>
                        <li>
                            <a href="#">Java</a>
                        </li>
                        <li>
                            <a href="#">笔记</a>
                        </li>
                        <li>
                            <a href="#">文档</a>
                        </li>
                        <li>
                            <a href="#">AngularJS</a>
                        </li>
                        <li>
                            <a href="#">CSS</a>
                        </li>
                        <li>
                            <a href="#">JavaScript</a>
                        </li>
                        <li>
                            <a href="#">Snippet</a>
                        </li>
                        <li>
                            <a href="#">jQuery</a>
                        </li>
                    </ul>
                </div>
                <div class="rss">
                    <a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2017 - Collect from <a href="http://www.cssmoban.com/"
                                                                  target="_blank" title="模板之家">模板之家</a>
                    - Modified by <a href="http://zmrenwu.com/" title="网页模板" target="_blank">追梦人物的博客</a>
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="{%url 'index' %}">首页</a></li>
            <li><a href="{% url 'full_width' %}">博客</a></li>
            <li><a href="{% url 'about' %}">关于</a></li>
            <li><a href="{% url 'contact' %}">联系</a></li>
        </ul>
    </nav>
</div>

<script src="{% static '/blog/js/script.js'%}"></script>

</body>
</html>

blogproject/templates/blog/full-width.html
{%extends 'base.html'  %}
{% load static %}
{% block main %}
    <article class="post post-1">
							<header class="entry-header">
								<h1 class="entry-title">
									<a href="detail.html">Adaptive Vs. Responsive Layouts And Optimal Text Readability</a>
								</h1>
								<div class="entry-meta">
									<span class="post-category"><a href="#">Web Design</a></span>

									<span class="post-date"><a href="#"><time class="entry-date" datetime="2012-11-09T23:15:57+00:00">February 2, 2013</time></a></span>

									<span class="post-author"><a href="#">Albert Einstein</a></span>

									<span class="comments-link"><a href="">4 Comments</a></span>
								</div>
							</header>
							<div class="entry-content clearfix">
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<div class="read-more cl-effect-14">
									<a href="#" class="more-link">Continue reading <span class="meta-nav">→</span></a>
								</div>
							</div>
						</article>

						<article class="post post-2">
							<header class="entry-header">
								<h1 class="entry-title">
									<a href="detail.html">Adaptive Vs. Responsive Layouts And Optimal Text Readability</a>
								</h1>
								<div class="entry-meta">
									<span class="post-category"><a href="#">Web Design</a></span>

									<span class="post-date"><a href="#"><time class="entry-date" datetime="2012-11-09T23:15:57+00:00">February 2, 2013</time></a></span>

									<span class="post-author"><a href="#">Albert Einstein</a></span>

									<span class="comments-link"><a href="#">4 Comments</a></span>
								</div>
							</header>
							<div class="entry-content clearfix">
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<div class="read-more cl-effect-14">
									<a href="#" class="more-link">Continue reading <span class="meta-nav">→</span></a>
								</div>
							</div>
						</article>

						<article class="post post-3">
							<header class="entry-header">
								<h1 class="entry-title">
									<a href="detail.html">Adaptive Vs. Responsive Layouts And Optimal Text Readability</a>
								</h1>
								<div class="entry-meta">
									<span class="post-category"><a href="#" rel="category tag">Web Design</a></span>

									<span class="post-date"><a href="#"><time class="entry-date" datetime="2012-11-09T23:15:57+00:00">February 2, 2013</time></a></span>

									<span class="post-author"><a href="#">Albert Einstein</a></span>

									<span class="comments-link"><a href="#">4 Comments</a></span>
								</div>
							</header>
							<div class="entry-content clearfix">
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<div class="read-more cl-effect-14">
									<a href="#" class="more-link">Continue reading <span class="meta-nav">→</span></a>
								</div>
							</div>
						</article>

						<article class="post post-4">
							<header class="entry-header">
								<h1 class="entry-title">
									<a href="detail.html">Adaptive Vs. Responsive Layouts And Optimal Text Readability</a>
								</h1>
								<div class="entry-meta">
									<span class="post-category"><a href="#" rel="category tag">Web Design</a></span>

									<span class="post-date"><a href="#"><time class="entry-date" datetime="2012-11-09T23:15:57+00:00">February 2, 2013</time></a></span>

									<span class="post-author"><a href="#">Albert Einstein</a></span>

									<span class="comments-link"><a href="#">4 Comments</a></span>
								</div>
							</header>
							<div class="entry-content clearfix">
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<div class="read-more cl-effect-14">
									<a href="#" class="more-link">Continue reading <span class="meta-nav">→</span></a>
								</div>
							</div>
						</article>
{% endblock main %}